//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Euro2016.DatabaseEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class country
    {
        public country()
        {
            this.team = new HashSet<team>();
        }
    
        public int Idt { get; set; }
        public string Cod { get; set; }
        public string Lbl { get; set; }
        public byte[] Flag { get; set; }
    
        public virtual ICollection<team> team { get; set; }
    }
}
