//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Euro2016.DatabaseEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class groupsmatchschedule
    {
        public short Idt { get; set; }
        public short MatchDay { get; set; }
        public short NumOrderHome { get; set; }
        public Nullable<short> NumOrderAway { get; set; }
    }
}
