//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Euro2016.DatabaseEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parameters
    {
        public string Name { get; set; }
        public string Value { get; set; }
    }
}
