//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Euro2016.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class players
    {
        public int Idt { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public Nullable<short> Number { get; set; }
        public int Team_Idt { get; set; }
    }
}
