//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Euro2016.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPool
    {
        public int Idt { get; set; }
        public int Pool_Idt { get; set; }
        public int User_Idt { get; set; }
    
        public virtual Pool Pool { get; set; }
        public virtual Usr Usr { get; set; }
    }
}
