//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Euro2016.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserStandings
    {
        public string Usr_Name { get; set; }
        public Nullable<int> Nbr { get; set; }
        public Nullable<int> PointsTotal { get; set; }
        public Nullable<int> NbrMatchNonJoues { get; set; }
    }
}
